#!/bin/bash

# Cluster workflow for Large Dephasing P=0.5 jobs (L=20,24,28,32,36)
# Reference script - run commands individually on cluster

echo "================================================"
echo "Large Dephasing P=0.5 Cluster Workflow"
echo "================================================"
echo ""
echo "Step 1: SSH to cluster and navigate to project"
echo "  ssh ap40.uw.osg-htc.org"
echo "  cd ~/binder-parameter-OSpool"
echo ""
echo "Step 2: Pull latest code from GitHub"
echo "  git pull origin main"
echo ""
echo "Step 3: Submit large dephasing P=0.5 jobs (225 jobs)"
echo "  cd jobs"
echo "  condor_submit large_dephasing_p05_jobs.submit"
echo ""
echo "Step 4: Monitor job progress"
echo "  condor_q"
echo "  # Or watch continuously:"
echo "  watch -n 30 condor_q"
echo ""
echo "Step 5: Check for completion (wait until all 225 jobs finish)"
echo "  condor_q | grep large_dephasing_p05"
echo ""
echo "Step 6: Collect results after all jobs complete"
echo "  bash collect_large_dephasing_p05_results.sh"
echo ""
echo "Step 7: Transfer results back to Mac"
echo "  wormhole send large_dephasing_p05_results_*.tar.gz"
echo "  # Note the wormhole code (e.g., 4-example-code)"
echo ""
echo "Step 8: On Mac, receive results"
echo "  cd ~/Desktop/binder-parameter-OSpool"
echo "  wormhole receive <code-from-step-7>"
echo ""
echo "================================================"
echo "Job Details:"
echo "  Total jobs: 225"
echo "  L values: 20, 24, 28, 32, 36"
echo "  λ values: 15 points (0.1 to 0.9)"
echo "  Samples: 3 per configuration"
echo "  P_x: 0.5 (dephasing strength)"
echo "  Seeds: 7001-7225"
echo "  Resources: 4 CPUs, 12 GB RAM, 48h timeout"
echo "================================================"
